# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'layout.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1150, 650)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.serial_refresh_btn = QPushButton(self.centralwidget)
        self.serial_refresh_btn.setObjectName(u"serial_refresh_btn")
        self.serial_refresh_btn.setGeometry(QRect(150, 40, 101, 21))
        self.serial_combo = QComboBox(self.centralwidget)
        self.serial_combo.setObjectName(u"serial_combo")
        self.serial_combo.setGeometry(QRect(10, 41, 131, 21))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 101, 20))
        self.serial_connect_btn = QPushButton(self.centralwidget)
        self.serial_connect_btn.setObjectName(u"serial_connect_btn")
        self.serial_connect_btn.setGeometry(QRect(260, 40, 101, 21))
        self.command_output_short = QTextBrowser(self.centralwidget)
        self.command_output_short.setObjectName(u"command_output_short")
        self.command_output_short.setGeometry(QRect(10, 570, 441, 71))
        self.command_output_short.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 510, 101, 20))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 550, 101, 20))
        self.forward_btn = QPushButton(self.centralwidget)
        self.forward_btn.setObjectName(u"forward_btn")
        self.forward_btn.setGeometry(QRect(60, 110, 41, 41))
        self.backward_btn = QPushButton(self.centralwidget)
        self.backward_btn.setObjectName(u"backward_btn")
        self.backward_btn.setGeometry(QRect(60, 160, 41, 41))
        self.turn_left_btn = QPushButton(self.centralwidget)
        self.turn_left_btn.setObjectName(u"turn_left_btn")
        self.turn_left_btn.setGeometry(QRect(10, 160, 41, 41))
        self.turn_right_btn = QPushButton(self.centralwidget)
        self.turn_right_btn.setObjectName(u"turn_right_btn")
        self.turn_right_btn.setGeometry(QRect(110, 160, 41, 41))
        self.get_azimuth_btn = QPushButton(self.centralwidget)
        self.get_azimuth_btn.setObjectName(u"get_azimuth_btn")
        self.get_azimuth_btn.setGeometry(QRect(440, 130, 101, 21))
        self.beep_btn = QPushButton(self.centralwidget)
        self.beep_btn.setObjectName(u"beep_btn")
        self.beep_btn.setGeometry(QRect(320, 100, 101, 21))
        self.get_distance_btn = QPushButton(self.centralwidget)
        self.get_distance_btn.setObjectName(u"get_distance_btn")
        self.get_distance_btn.setGeometry(QRect(320, 130, 101, 21))
        self.kill_btn = QPushButton(self.centralwidget)
        self.kill_btn.setObjectName(u"kill_btn")
        self.kill_btn.setGeometry(QRect(440, 160, 101, 20))
        self.print_siema_btn = QPushButton(self.centralwidget)
        self.print_siema_btn.setObjectName(u"print_siema_btn")
        self.print_siema_btn.setGeometry(QRect(440, 100, 101, 21))
        self.send_btn = QPushButton(self.centralwidget)
        self.send_btn.setObjectName(u"send_btn")
        self.send_btn.setGeometry(QRect(470, 530, 71, 21))
        self.command_input = QLineEdit(self.centralwidget)
        self.command_input.setObjectName(u"command_input")
        self.command_input.setGeometry(QRect(10, 530, 441, 21))
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 70, 541, 21))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 80, 121, 20))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 0, 161, 20))
        self.tab_container = QTabWidget(self.centralwidget)
        self.tab_container.setObjectName(u"tab_container")
        self.tab_container.setGeometry(QRect(559, 10, 580, 630))
        self.tab_2d = QWidget()
        self.tab_2d.setObjectName(u"tab_2d")
        self.gridLayoutWidget_3 = QWidget(self.tab_2d)
        self.gridLayoutWidget_3.setObjectName(u"gridLayoutWidget_3")
        self.gridLayoutWidget_3.setGeometry(QRect(10, 10, 561, 581))
        self.grid_2d_layout = QGridLayout(self.gridLayoutWidget_3)
        self.grid_2d_layout.setObjectName(u"grid_2d_layout")
        self.grid_2d_layout.setContentsMargins(0, 0, 0, 0)
        self.tab_container.addTab(self.tab_2d, "")
        self.tab_3d = QWidget()
        self.tab_3d.setObjectName(u"tab_3d")
        self.gridLayoutWidget_2 = QWidget(self.tab_3d)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(10, 10, 561, 581))
        self.grid_3d_layout = QGridLayout(self.gridLayoutWidget_2)
        self.grid_3d_layout.setObjectName(u"grid_3d_layout")
        self.grid_3d_layout.setContentsMargins(0, 0, 0, 0)
        self.tab_container.addTab(self.tab_3d, "")
        self.tab_raw = QWidget()
        self.tab_raw.setObjectName(u"tab_raw")
        self.command_output_long = QTextBrowser(self.tab_raw)
        self.command_output_long.setObjectName(u"command_output_long")
        self.command_output_long.setGeometry(QRect(10, 10, 561, 581))
        self.command_output_long.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.tab_container.addTab(self.tab_raw, "")
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 490, 161, 20))
        self.tower_slider = QSlider(self.centralwidget)
        self.tower_slider.setObjectName(u"tower_slider")
        self.tower_slider.setGeometry(QRect(10, 210, 141, 21))
        self.tower_slider.setMinimum(0)
        self.tower_slider.setMaximum(180)
        self.tower_slider.setValue(90)
        self.tower_slider.setOrientation(Qt.Horizontal)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(10, 480, 541, 21))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.connection_status_label = QLabel(self.centralwidget)
        self.connection_status_label.setObjectName(u"connection_status_label")
        self.connection_status_label.setGeometry(QRect(380, 20, 51, 51))
        font = QFont()
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QFont.PreferDefault)
        self.connection_status_label.setFont(font)
        self.connection_status_label.setAlignment(Qt.AlignCenter)
        self.connection_status_label.setMargin(0)
        self.scan_btn = QPushButton(self.centralwidget)
        self.scan_btn.setObjectName(u"scan_btn")
        self.scan_btn.setGeometry(QRect(320, 160, 101, 21))
        self.turn_left_step_btn = QPushButton(self.centralwidget)
        self.turn_left_step_btn.setObjectName(u"turn_left_step_btn")
        self.turn_left_step_btn.setGeometry(QRect(10, 320, 41, 41))
        self.backward_step_btn = QPushButton(self.centralwidget)
        self.backward_step_btn.setObjectName(u"backward_step_btn")
        self.backward_step_btn.setGeometry(QRect(60, 320, 41, 41))
        self.forward_step_btn = QPushButton(self.centralwidget)
        self.forward_step_btn.setObjectName(u"forward_step_btn")
        self.forward_step_btn.setGeometry(QRect(60, 270, 41, 41))
        self.turn_right_step_btn = QPushButton(self.centralwidget)
        self.turn_right_step_btn.setObjectName(u"turn_right_step_btn")
        self.turn_right_step_btn.setGeometry(QRect(110, 320, 41, 41))
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 240, 151, 20))
        self.drive_step_slider = QSlider(self.centralwidget)
        self.drive_step_slider.setObjectName(u"drive_step_slider")
        self.drive_step_slider.setGeometry(QRect(10, 430, 141, 21))
        self.drive_step_slider.setMinimum(1)
        self.drive_step_slider.setMaximum(30)
        self.drive_step_slider.setValue(10)
        self.drive_step_slider.setOrientation(Qt.Horizontal)
        self.rotate_step_slider = QSlider(self.centralwidget)
        self.rotate_step_slider.setObjectName(u"rotate_step_slider")
        self.rotate_step_slider.setGeometry(QRect(10, 400, 141, 21))
        self.rotate_step_slider.setMinimum(10)
        self.rotate_step_slider.setMaximum(90)
        self.rotate_step_slider.setSingleStep(1)
        self.rotate_step_slider.setValue(30)
        self.rotate_step_slider.setOrientation(Qt.Horizontal)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(200, 210, 101, 20))
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(200, 430, 101, 20))
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(200, 400, 101, 20))
        self.rotate_to_slider = QSlider(self.centralwidget)
        self.rotate_to_slider.setObjectName(u"rotate_to_slider")
        self.rotate_to_slider.setGeometry(QRect(10, 370, 141, 21))
        self.rotate_to_slider.setMinimum(0)
        self.rotate_to_slider.setMaximum(360)
        self.rotate_to_slider.setSingleStep(1)
        self.rotate_to_slider.setValue(180)
        self.rotate_to_slider.setOrientation(Qt.Horizontal)
        self.rotate_to_btn = QPushButton(self.centralwidget)
        self.rotate_to_btn.setObjectName(u"rotate_to_btn")
        self.rotate_to_btn.setGeometry(QRect(200, 370, 101, 21))
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(160, 400, 31, 21))
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(160, 430, 31, 21))
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(160, 370, 31, 21))
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(160, 210, 31, 21))
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(10, 230, 301, 21))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(300, 80, 20, 411))
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(320, 80, 121, 20))
        MainWindow.setCentralWidget(self.centralwidget)
        QWidget.setTabOrder(self.serial_combo, self.serial_refresh_btn)
        QWidget.setTabOrder(self.serial_refresh_btn, self.serial_connect_btn)
        QWidget.setTabOrder(self.serial_connect_btn, self.forward_btn)
        QWidget.setTabOrder(self.forward_btn, self.turn_left_btn)
        QWidget.setTabOrder(self.turn_left_btn, self.backward_btn)
        QWidget.setTabOrder(self.backward_btn, self.turn_right_btn)
        QWidget.setTabOrder(self.turn_right_btn, self.get_distance_btn)
        QWidget.setTabOrder(self.get_distance_btn, self.get_azimuth_btn)
        QWidget.setTabOrder(self.get_azimuth_btn, self.beep_btn)
        QWidget.setTabOrder(self.beep_btn, self.print_siema_btn)
        QWidget.setTabOrder(self.print_siema_btn, self.kill_btn)
        QWidget.setTabOrder(self.kill_btn, self.command_input)
        QWidget.setTabOrder(self.command_input, self.send_btn)
        QWidget.setTabOrder(self.send_btn, self.command_output_short)
        QWidget.setTabOrder(self.command_output_short, self.tab_container)
        QWidget.setTabOrder(self.tab_container, self.command_output_long)
        QWidget.setTabOrder(self.command_output_long, self.tower_slider)

        self.retranslateUi(MainWindow)
        self.rotate_step_slider.valueChanged.connect(self.label_14.setNum)
        self.drive_step_slider.sliderMoved.connect(self.label_15.setNum)
        self.rotate_to_slider.valueChanged.connect(self.label_16.setNum)
        self.tower_slider.valueChanged.connect(self.label_17.setNum)

        self.tab_container.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"ScanBot Control Application", None))
        self.serial_refresh_btn.setText(QCoreApplication.translate("MainWindow", u"refresh", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"choose serial port", None))
        self.serial_connect_btn.setText(QCoreApplication.translate("MainWindow", u"connect", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"command line", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"output", None))
        self.forward_btn.setText(QCoreApplication.translate("MainWindow", u"^", None))
        self.backward_btn.setText(QCoreApplication.translate("MainWindow", u"\\/", None))
        self.turn_left_btn.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.turn_right_btn.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.get_azimuth_btn.setText(QCoreApplication.translate("MainWindow", u"GET_AZIMUTH", None))
        self.beep_btn.setText(QCoreApplication.translate("MainWindow", u"BEEP", None))
#if QT_CONFIG(shortcut)
        self.beep_btn.setShortcut(QCoreApplication.translate("MainWindow", u"Space", None))
#endif // QT_CONFIG(shortcut)
        self.get_distance_btn.setText(QCoreApplication.translate("MainWindow", u"GET_DISTANCE", None))
        self.kill_btn.setText(QCoreApplication.translate("MainWindow", u"KILL", None))
        self.print_siema_btn.setText(QCoreApplication.translate("MainWindow", u"PRINT SIEMA", None))
        self.send_btn.setText(QCoreApplication.translate("MainWindow", u"SEND", None))
#if QT_CONFIG(shortcut)
        self.send_btn.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"RAW CONTROL", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"CONNECTION", None))
        self.tab_container.setTabText(self.tab_container.indexOf(self.tab_2d), QCoreApplication.translate("MainWindow", u"2D view", None))
        self.tab_container.setTabText(self.tab_container.indexOf(self.tab_3d), QCoreApplication.translate("MainWindow", u"3D view", None))
        self.tab_container.setTabText(self.tab_container.indexOf(self.tab_raw), QCoreApplication.translate("MainWindow", u"raw output", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"CONSOLE", None))
        self.connection_status_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">\u274c</p></body></html>", None))
        self.scan_btn.setText(QCoreApplication.translate("MainWindow", u"SCAN", None))
#if QT_CONFIG(shortcut)
        self.scan_btn.setShortcut(QCoreApplication.translate("MainWindow", u"Space", None))
#endif // QT_CONFIG(shortcut)
        self.turn_left_step_btn.setText(QCoreApplication.translate("MainWindow", u"<", None))
#if QT_CONFIG(shortcut)
        self.turn_left_step_btn.setShortcut(QCoreApplication.translate("MainWindow", u"A", None))
#endif // QT_CONFIG(shortcut)
        self.backward_step_btn.setText(QCoreApplication.translate("MainWindow", u"\\/", None))
#if QT_CONFIG(shortcut)
        self.backward_step_btn.setShortcut(QCoreApplication.translate("MainWindow", u"S", None))
#endif // QT_CONFIG(shortcut)
        self.forward_step_btn.setText(QCoreApplication.translate("MainWindow", u"^", None))
#if QT_CONFIG(shortcut)
        self.forward_step_btn.setShortcut(QCoreApplication.translate("MainWindow", u"W", None))
#endif // QT_CONFIG(shortcut)
        self.turn_right_step_btn.setText(QCoreApplication.translate("MainWindow", u">", None))
#if QT_CONFIG(shortcut)
        self.turn_right_step_btn.setShortcut(QCoreApplication.translate("MainWindow", u"D", None))
#endif // QT_CONFIG(shortcut)
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"ODOMETRIC CONTROL", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"tower position", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"drive step", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"rotate step", None))
        self.rotate_to_btn.setText(QCoreApplication.translate("MainWindow", u"ROTATE TO", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"30", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"180", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"90", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"FUNCTIONS", None))
    # retranslateUi

