version: '3'
services:
  roscore:
    hostname: roscore
    build: ros-core
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: xterm -fa Monospace -fs 10 -bg blue -fg white -e "roscore"

  rosconsole:
    hostname: rosconsole
    build: ros-console
    depends_on:
      - "roscore"
    environment:
      ROS_MASTER_URI: "http://roscore:11311"
      DISPLAY: ${DISPLAY}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      QT_X11_NO_MITSHM: 1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: xterm -fa Monospace -fs 10 -bg black -fg green

  laserbcast:
    hostname: laserbcast
    build: laser-bcast
    depends_on:
      - "roscore"
    environment:
      ROS_MASTER_URI: "http://roscore:11311"
      DISPLAY: ${DISPLAY}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      QT_X11_NO_MITSHM: 1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: xterm -fa Monospace -fs 10 -bg white -fg black -e 'rosrun --debug tf static_transform_publisher 0 0 0 0 0 0 base_link base_laser 100'

  gmapping:
    hostname: gmapping
    build: slam-gmapping
    depends_on:
      - "roscore"
    environment:
      ROS_MASTER_URI: "http://roscore:11311"
      DISPLAY: ${DISPLAY}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      QT_X11_NO_MITSHM: 1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: xterm -fa Monospace -fs 10 -bg brown -fg orange -e 'rosrun --debug gmapping slam_gmapping scan:=scan _map_update_interval:=0.1 _maxUrange:=5.0 _kernel_size:=2 _delta:=0.05 output="screen"'

  rviz:
    hostname: rviz
    build: rviz
    depends_on:
      - "roscore"
    environment:
      ROS_MASTER_URI: "http://roscore:11311"
      DISPLAY: ${DISPLAY}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      QT_X11_NO_MITSHM: 1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: rviz -d /app/rviz-config.rviz

  gazebo:
    build: gazebo
    environment:
      ROS_MASTER_URI: "http://roscore:11311"
      DISPLAY: ${DISPLAY}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      QT_X11_NO_MITSHM: 1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:${DOCKER_HOME}/.Xauthority
    command: bash -c "gazebo"

networks:
  default:
    external:
      name: scanbot-network
