#!/bin/bash -axe
test -n "$GMAPPING_scan"
test -n "$GMAPPING__throttle_scans"
test -n "$GMAPPING__base_frame"
test -n "$GMAPPING__map_frame"
test -n "$GMAPPING__odom_frame"
test -n "$GMAPPING__map_update_interval"
test -n "$GMAPPING__maxUrange"
test -n "$GMAPPING__sigma"
test -n "$GMAPPING__kernelSize"
test -n "$GMAPPING__lstep"
test -n "$GMAPPING__astep"
test -n "$GMAPPING__iterations"
test -n "$GMAPPING__lsigma"
test -n "$GMAPPING__ogain"
test -n "$GMAPPING__lskip"
test -n "$GMAPPING__minimumScore"
test -n "$GMAPPING__srr"
test -n "$GMAPPING__srt"
test -n "$GMAPPING__str"
test -n "$GMAPPING__stt"
test -n "$GMAPPING__linearUpdate"
test -n "$GMAPPING__angularUpdate"
test -n "$GMAPPING__temporalUpdate"
test -n "$GMAPPING__resampleThreshold"
test -n "$GMAPPING__particles"
test -n "$GMAPPING__xmin"
test -n "$GMAPPING__ymin"
test -n "$GMAPPING__xmax"
test -n "$GMAPPING__ymax"
test -n "$GMAPPING__delta"
test -n "$GMAPPING__llsamplerange"
test -n "$GMAPPING__llsamplestep"
test -n "$GMAPPING__lasamplerange"
test -n "$GMAPPING__lasamplestep"
test -n "$GMAPPING__transform_publish_period"
test -n "$GMAPPING__occ_thresh"
test -n "$GMAPPING__maxRange"

rosrun gmapping slam_gmapping \
    scan:="$GMAPPING_scan" \
    _throttle_scans:="$GMAPPING__throttle_scans" \
    _base_frame:="$GMAPPING__base_frame" \
    _map_frame:="$GMAPPING__map_frame" \
    _odom_frame:="$GMAPPING__odom_frame" \
    _map_update_interval:="$GMAPPING__map_update_interval" \
    _maxUrange:="$GMAPPING__maxUrange" \
    _sigma:="$GMAPPING__sigma" \
    _kernelSize:="$GMAPPING__kernelSize" \
    _lstep:="$GMAPPING__lstep" \
    _astep:="$GMAPPING__astep" \
    _iterations:="$GMAPPING__iterations" \
    _lsigma:="$GMAPPING__lsigma" \
    _ogain:="$GMAPPING__ogain" \
    _lskip:="$GMAPPING__lskip" \
    _minimumScore:="$GMAPPING__minimumScore" \
    _srr:="$GMAPPING__srr" \
    _srt:="$GMAPPING__srt" \
    _str:="$GMAPPING__str" \
    _stt:="$GMAPPING__stt" \
    _linearUpdate:="$GMAPPING__linearUpdate" \
    _angularUpdate:="$GMAPPING__angularUpdate" \
    _temporalUpdate:="$GMAPPING__temporalUpdate" \
    _resampleThreshold:="$GMAPPING__resampleThreshold" \
    _particles:="$GMAPPING__particles" \
    _xmin:="$GMAPPING__xmin" \
    _ymin:="$GMAPPING__ymin" \
    _xmax:="$GMAPPING__xmax" \
    _ymax:="$GMAPPING__ymax" \
    _delta:="$GMAPPING__delta" \
    _llsamplerange:="$GMAPPING__llsamplerange" \
    _llsamplestep:="$GMAPPING__llsamplestep" \
    _lasamplerange:="$GMAPPING__lasamplerange" \
    _lasamplestep:="$GMAPPING__lasamplestep" \
    _transform_publish_period:="$GMAPPING__transform_publish_period" \
    _occ_thresh:="$GMAPPING__occ_thresh" \
    _maxRange:="$GMAPPING__maxRange" \
