#!/bin/bash -ae
test -n "$gmapping_scan"
test -n "$gmapping__throttle_scans"
test -n "$gmapping__base_frame"
test -n "$gmapping__map_frame"
test -n "$gmapping__odom_frame"
test -n "$gmapping__map_update_interval"
test -n "$gmapping__maxUrange"
test -n "$gmapping__sigma"
test -n "$gmapping__kernelSize"
test -n "$gmapping__lstep"
test -n "$gmapping__astep"
test -n "$gmapping__iterations"
test -n "$gmapping__lsigma"
test -n "$gmapping__ogain"
test -n "$gmapping__lskip"
test -n "$gmapping__minimumScore"
test -n "$gmapping__srr"
test -n "$gmapping__srt"
test -n "$gmapping__str"
test -n "$gmapping__stt"
test -n "$gmapping__linearUpdate"
test -n "$gmapping__angularUpdate"
test -n "$gmapping__temporalUpdate"
test -n "$gmapping__resampleThreshold"
test -n "$gmapping__particles"
test -n "$gmapping__xmin"
test -n "$gmapping__ymin"
test -n "$gmapping__xmax"
test -n "$gmapping__ymax"
test -n "$gmapping__delta"
test -n "$gmapping__llsamplerange"
test -n "$gmapping__llsamplestep"
test -n "$gmapping__lasamplerange"
test -n "$gmapping__lasamplestep"
test -n "$gmapping__transform_publish_period"
test -n "$gmapping__occ_thresh"
test -n "$gmapping__maxRange"
set -x
exec rosrun gmapping slam_gmapping \
    scan:="$gmapping_scan" \
    _throttle_scans:="$gmapping__throttle_scans" \
    _base_frame:="$gmapping__base_frame" \
    _map_frame:="$gmapping__map_frame" \
    _odom_frame:="$gmapping__odom_frame" \
    _map_update_interval:="$gmapping__map_update_interval" \
    _maxUrange:="$gmapping__maxUrange" \
    _sigma:="$gmapping__sigma" \
    _kernelSize:="$gmapping__kernelSize" \
    _lstep:="$gmapping__lstep" \
    _astep:="$gmapping__astep" \
    _iterations:="$gmapping__iterations" \
    _lsigma:="$gmapping__lsigma" \
    _ogain:="$gmapping__ogain" \
    _lskip:="$gmapping__lskip" \
    _minimumScore:="$gmapping__minimumScore" \
    _srr:="$gmapping__srr" \
    _srt:="$gmapping__srt" \
    _str:="$gmapping__str" \
    _stt:="$gmapping__stt" \
    _linearUpdate:="$gmapping__linearUpdate" \
    _angularUpdate:="$gmapping__angularUpdate" \
    _temporalUpdate:="$gmapping__temporalUpdate" \
    _resampleThreshold:="$gmapping__resampleThreshold" \
    _particles:="$gmapping__particles" \
    _xmin:="$gmapping__xmin" \
    _ymin:="$gmapping__ymin" \
    _xmax:="$gmapping__xmax" \
    _ymax:="$gmapping__ymax" \
    _delta:="$gmapping__delta" \
    _llsamplerange:="$gmapping__llsamplerange" \
    _llsamplestep:="$gmapping__llsamplestep" \
    _lasamplerange:="$gmapping__lasamplerange" \
    _lasamplestep:="$gmapping__lasamplestep" \
    _transform_publish_period:="$gmapping__transform_publish_period" \
    _occ_thresh:="$gmapping__occ_thresh" \
    _maxRange:="$gmapping__maxRange" \
