#!/bin/bash -axe
test -n "$hector_scan"
test -n "$hector__base_frame"
test -n "$hector__map_frame"
test -n "$hector__odom_frame"
test -n "$hector__map_resolution"
test -n "$hector__map_size"
test -n "$hector__map_start_x"
test -n "$hector__map_start_y"
test -n "$hector__map_update_distance_thresh"
test -n "$hector__map_update_angle_thresh"
test -n "$hector__map_pub_period"
test -n "$hector__map_multi_res_levels"
test -n "$hector__update_factor_free"
test -n "$hector__update_factor_occupied"
test -n "$hector__laser_min_dist"
test -n "$hector__laser_max_dist"
test -n "$hector__laser_z_min_value"
test -n "$hector__laser_z_max_value"
test -n "$hector__pub_map_odom_transform"
test -n "$hector__output_timing"
test -n "$hector__scan_subscriber_queue_size"
test -n "$hector__pub_map_scanmatch_transform"
test -n "$hector__tf_map_scanmatch_transform_frame_name"

exec rosrun hector_mapping hector_mapping \
    scan:="$hector_scan" \
    _base_frame:="$hector__base_frame" \
    _map_frame:="$hector__map_frame" \
    _odom_frame:="$hector__odom_frame" \
    _map_resolution:="$hector__map_resolution" \
    _map_size:="$hector__map_size" \
    _map_start_x:="$hector__map_start_x" \
    _map_start_y:="$hector__map_start_y" \
    _map_update_distance_thresh:="$hector__map_update_distance_thresh" \
    _map_update_angle_thresh:="$hector__map_update_angle_thresh" \
    _map_pub_period:="$hector__map_pub_period" \
    _map_multi_res_levels:="$hector__map_multi_res_levels" \
    _update_factor_free:="$hector__update_factor_free" \
    _update_factor_occupied:="$hector__update_factor_occupied" \
    _laser_min_dist:="$hector__laser_min_dist" \
    _laser_max_dist:="$hector__laser_max_dist" \
    _laser_z_min_value:="$hector__laser_z_min_value" \
    _laser_z_max_value:="$hector__laser_z_max_value" \
    _pub_map_odom_transform:="$hector__pub_map_odom_transform" \
    _output_timing:="$hector__output_timing" \
    _scan_subscriber_queue_size:="$hector__scan_subscriber_queue_size" \
    _pub_map_scanmatch_transform:="$hector__pub_map_scanmatch_transform" \
    _tf_map_scanmatch_transform_frame_name:="$hector__tf_map_scanmatch_transform_frame_name" \
