#!/bin/bash -axe
test -n "$HECTOR_scan"
test -n "$HECTOR__base_frame"
test -n "$HECTOR__map_frame"
test -n "$HECTOR__odom_frame"
test -n "$HECTOR__map_resolution"
test -n "$HECTOR__map_size"
test -n "$HECTOR__map_start_x"
test -n "$HECTOR__map_start_y"
test -n "$HECTOR__map_update_distance_thresh"
test -n "$HECTOR__map_update_angle_thresh"
test -n "$HECTOR__map_pub_period"
test -n "$HECTOR__map_multi_res_levels"
test -n "$HECTOR__update_factor_free"
test -n "$HECTOR__update_factor_occupied"
test -n "$HECTOR__laser_min_dist"
test -n "$HECTOR__laser_max_dist"
test -n "$HECTOR__laser_z_min_value"
test -n "$HECTOR__laser_z_max_value"
test -n "$HECTOR__pub_map_odom_transform"
test -n "$HECTOR__output_timing"
test -n "$HECTOR__scan_subscriber_queue_size"
test -n "$HECTOR__pub_map_scanmatch_transform"
test -n "$HECTOR__tf_map_scanmatch_transform_frame_name"

rosrun hector_mapping hector_mapping \
    scan:="$HECTOR_scan" \
    _base_frame:="$HECTOR__base_frame" \
    _map_frame:="$HECTOR__map_frame" \
    _odom_frame:="$HECTOR__odom_frame" \
    _map_resolution:="$HECTOR__map_resolution" \
    _map_size:="$HECTOR__map_size" \
    _map_start_x:="$HECTOR__map_start_x" \
    _map_start_y:="$HECTOR__map_start_y" \
    _map_update_distance_thresh:="$HECTOR__map_update_distance_thresh" \
    _map_update_angle_thresh:="$HECTOR__map_update_angle_thresh" \
    _map_pub_period:="$HECTOR__map_pub_period" \
    _map_multi_res_levels:="$HECTOR__map_multi_res_levels" \
    _update_factor_free:="$HECTOR__update_factor_free" \
    _update_factor_occupied:="$HECTOR__update_factor_occupied" \
    _laser_min_dist:="$HECTOR__laser_min_dist" \
    _laser_max_dist:="$HECTOR__laser_max_dist" \
    _laser_z_min_value:="$HECTOR__laser_z_min_value" \
    _laser_z_max_value:="$HECTOR__laser_z_max_value" \
    _pub_map_odom_transform:="$HECTOR__pub_map_odom_transform" \
    _output_timing:="$HECTOR__output_timing" \
    _scan_subscriber_queue_size:="$HECTOR__scan_subscriber_queue_size" \
    _pub_map_scanmatch_transform:="$HECTOR__pub_map_scanmatch_transform" \
    _tf_map_scanmatch_transform_frame_name:="$HECTOR__tf_map_scanmatch_transform_frame_name" \
