#!/bin/bash -axe
test -n "$karto_scan"
test -n "$karto__odom_frame"
test -n "$karto__map_frame"
test -n "$karto__base_frame"
test -n "$karto__throttle_scans"
test -n "$karto__map_update_interval"
test -n "$karto__delta"
test -n "$karto__transform_publish_period"
test -n "$karto__use_scan_matching"
test -n "$karto__use_scan_barycenter"
test -n "$karto__minimum_travel_distance"
test -n "$karto__minimum_travel_heading"
test -n "$karto__scan_buffer_size"
test -n "$karto__scan_buffer_maximum_scan_distance"
test -n "$karto__link_match_minimum_response_fine"
test -n "$karto__link_scan_maximum_distance"
test -n "$karto__loop_search_maximum_distance"
test -n "$karto__do_loop_closing"
test -n "$karto__loop_match_minimum_chain_size"
test -n "$karto__loop_match_maximum_variance_coarse"
test -n "$karto__loop_match_minimum_response_fine"
test -n "$karto__correlation_search_space_dimension"
test -n "$karto__correlation_search_space_resolution"
test -n "$karto__correlation_search_space_smear_deviation"
test -n "$karto__loop_search_space_resolution"
test -n "$karto__loop_search_space_smear_deviation"
test -n "$karto__distance_variance_penalty"
test -n "$karto__angle_variance_penalty"
test -n "$karto__fine_search_angle_offset"
test -n "$karto__coarse_search_angle_offset"
test -n "$karto__coarse_angle_resolution"
test -n "$karto__minimum_angle_penalty"
test -n "$karto__use_response_expansion"
#test -n "$karto__loop_search_space_dimension"
#test -n "$karto__minimum_distance_penalty"

exec rosrun slam_karto slam_karto \
    scan:="$karto_scan" \
    _odom_frame:="$karto__odom_frame" \
    _map_frame:="$karto__map_frame" \
    _base_frame:="$karto__base_frame" \
    _throttle_scans:="$karto__throttle_scans" \
    _map_update_interval:="$karto__map_update_interval" \
    _delta:="$karto__delta" \
    _transform_publish_period:="$karto__transform_publish_period" \
    _use_scan_matching:="$karto__use_scan_matching" \
    _use_scan_barycenter:="$karto__use_scan_barycenter" \
    _minimum_travel_distance:="$karto__minimum_travel_distance" \
    _minimum_travel_heading:="$karto__minimum_travel_heading" \
    _scan_buffer_size:="$karto__scan_buffer_size" \
    _scan_buffer_maximum_scan_distance:="$karto__scan_buffer_maximum_scan_distance" \
    _link_match_minimum_response_fine:="$karto__link_match_minimum_response_fine" \
    _link_scan_maximum_distance:="$karto__link_scan_maximum_distance" \
    _loop_search_maximum_distance:="$karto__loop_search_maximum_distance" \
    _do_loop_closing:="$karto__do_loop_closing" \
    _loop_match_minimum_chain_size:="$karto__loop_match_minimum_chain_size" \
    _loop_match_maximum_variance_coarse:="$karto__loop_match_maximum_variance_coarse" \
    _loop_match_minimum_response_fine:="$karto__loop_match_minimum_response_fine" \
    _correlation_search_space_dimension:="$karto__correlation_search_space_dimension" \
    _correlation_search_space_resolution:="$karto__correlation_search_space_resolution" \
    _correlation_search_space_smear_deviation:="$karto__correlation_search_space_smear_deviation" \
    _loop_search_space_resolution:="$karto__loop_search_space_resolution" \
    _loop_search_space_smear_deviation:="$karto__loop_search_space_smear_deviation" \
    _distance_variance_penalty:="$karto__distance_variance_penalty" \
    _angle_variance_penalty:="$karto__angle_variance_penalty" \
    _fine_search_angle_offset:="$karto__fine_search_angle_offset" \
    _coarse_search_angle_offset:="$karto__coarse_search_angle_offset" \
    _coarse_angle_resolution:="$karto__coarse_angle_resolution" \
    _minimum_angle_penalty:="$karto__minimum_angle_penalty" \
    _use_response_expansion:="$karto__use_response_expansion" \
#   _loop_search_space_dimension:="$karto__loop_search_space_dimension" \ # setting this parameter caused segfault in slam_karto
#    _minimum_distance_penalty:="$karto__minimum_distance_penalty" \ # setting this parameter caused segfault in slam_karto
